its working!

diff --git a/bin/install-magento b/bin/install-magento
--- a/bin/install-magento
+++ b/bin/install-magento
@@ -24,17 +24,20 @@ else
 	EXITCODE=$?; if [[ $EXITCODE != 0 ]]; then exit $EXITCODE; fi
 	echo "Magento 1.9 installed";
 	cd /var/www/html
-	if [ -d ".modman" ]; then
-		echo "Enabling symlinks in Magento";
-		n98-magerun dev:symlinks --on --global
+	if ! [ -d "./.modman" ]; then
+		echo "modman not found."
 		echo "Installing modman";
 		bash < <(curl -s -L https://raw.github.com/colinmollenhour/modman/master/modman-installer)
-		source ~/.profile
 		echo "Setting up modman + sailthru";
+		source ~/.profile
 		modman init  
 		modman link /var/www/sailthru
+		echo "Enabling symlinks in Magento";
+		n98-magerun dev:symlinks --on --global
 		echo "Finished Sailthru setup"
 	fi
 fi
+echo "Re-owning files"
 chown -R www-data:www-data /var/www/html
+echo "Starting Apache"
 apache2-foreground
